### ISSUE TITLE
Running balance displaying for debit, but not for credit 

### ISSUE THREAD

**Issue by sarmeyer** [michalmazur/chase-running-balance#1]
Thank you for this awesome extension - not sure why it's not part of Chase by default! I tried figuring out why this isn't working for the credit card account summary and thought initially it was timing out and therefore the method returned early. After some more testing, I don't see the log associated with that case. Have you experienced this? I realize it's difficult to send you an example of it to test.

Any help would be appreciated!

**Comment by michalmazur** [comment]
Could you clarify what you mean by the credit card account summary? It looks like the Online Banking has recently undergone another redesign and I want to make sure I understand you correctly. Are you referring to the page at https://secure***.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/multiProduct;flyout=accounts,*********,BAC?

As for the log, can you confirm that you can see at least "CRB: Enter main()"?

**Comment by sarmeyer** [comment]
Yes, that is the correct url. The balance column is showing for a debit account flyout, but not for a credit account flyout. I'm actually not seeing that log either. I see these 3 - 
```Slot Placement - Service.init() called with Page Id: cxo_account_dashboard ```
```Slot Placement - Calling XPO with Page Id: cxo_account_dashboard```
```Slot Placement - [adUpdate] Event Published for Page Id: cxo_account_dashboard```

**Comment by michalmazur** [comment]
The balance column should work on checking accounts because it's a built-in feature. However, there's definitely a problem with the flyout and I will look into it. 

It's interesting that you're not seeing "CRB: Enter main()" because that's one of the very first lines of code. It could be a separate problem. Could you check if the subdomain you're redirected to after login is listed in [manifest.json](https://github.com/michalmazur/chase-running-balance/blob/master/src/manifest.json)?

**Comment by michalmazur** [comment]
The problem with the flyout should be fixed in the newest version of the extension.

**Comment by sarmeyer** [comment]
Oh of course, I didn't realize the Debit flyout already had a running balance column. I upgraded and it works perfectly! Thanks for the quick fix.
